#pragma once
#include <windows.h>

enum class ConsoleColor
{
	ConsoleTextColor_Red = (FOREGROUND_RED | FOREGROUND_INTENSITY),
	ConsoleTextColor_Green = (FOREGROUND_GREEN | FOREGROUND_INTENSITY),
	ConsoleTextColor_Blue = (FOREGROUND_GREEN | FOREGROUND_INTENSITY),
	ConsoleTextColor_Magenta = (FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY),
	ConsoleTextColor_Yellow = (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY),
	ConsoleTextColor_Cyan = (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY),

	ConsoleTextColor_DarkRed = FOREGROUND_RED,
	ConsoleTextColor_DarkGreen = FOREGROUND_GREEN,
	ConsoleTextColor_DarkBlue = FOREGROUND_BLUE,
	ConsoleTextColor_DarkMagenta = (FOREGROUND_RED | FOREGROUND_BLUE),
	ConsoleTextColor_DarkYellow = (FOREGROUND_RED | FOREGROUND_GREEN),
	ConsoleTextColor_DarkCyan = (FOREGROUND_BLUE | FOREGROUND_GREEN),

	ConsoleTextColor_White = (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE),

	ConsoleBGColor_Red = (BACKGROUND_RED | BACKGROUND_INTENSITY),
	ConsoleBGColor_Green = (BACKGROUND_GREEN | BACKGROUND_INTENSITY),
	ConsoleBGColor_Blue = (BACKGROUND_BLUE | BACKGROUND_INTENSITY),
	ConsoleBGColor_Magenta = (BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY),
	ConsoleBGColor_Yellow = (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY),
	ConsoleBGColor_Cyan = (BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY),

	ConsoleBGColor_DarkRed = BACKGROUND_RED,
	ConsoleBGColor_DarkGreen = BACKGROUND_GREEN,
	ConsoleBGColor_DarkBlue = BACKGROUND_GREEN,
	ConsoleBGColor_DarkMagenta = (BACKGROUND_RED | BACKGROUND_BLUE),
	ConsoleBGColor_DarkYellow = (BACKGROUND_RED | BACKGROUND_GREEN),
	ConsoleBGColor_DarkCyan = (BACKGROUND_BLUE | BACKGROUND_GREEN),

	ConsoleBGColor_White = (BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE)
};